name: CI Pipeline
on: 
  push:
    branches:
      - main

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code 
        uses: actions/checkout@v4
 
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install dependencies 
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Run pytest 
        working-directory: backend
        run: pytest 
        
  security:
    name: DevSecOps Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code 
        uses: actions/checkout@v4
        
      - name: Run Bandit Security Scan
        working-directory: backend
        run: bandit -r . --exclude ./test_app.py

      - name: Run Dependency Vulnerability Test
        run: pip-audit

      - name: Run secret leak test
        uses: gitleaks/gitleaks-action@v2
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build & Publish Image
    runs-on: ubuntu-latest
    needs: [test, security]
    steps:      
      - name: Checkout the code 
        uses: actions/checkout@v4
        
      - name: Build Docker image
        working-directory: backend
        run: docker build -t devsecops-backend:v1 .    

 
      - name: Scan the built image
        uses: aquasecurity/trivy-action@v0.36.0
        with: 
          image-ref: devsecops-backend:v1
          format: 'sarif'
          version: 'v0.72.0'
          output: 'trivy-results.sarif'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Tag the image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker tag devsecops-backend:v1 ${{ secrets.DOCKERHUB_USERNAME }}/devsecops-backend:$IMAGE_TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devsecops-backend:$IMAGE_TAG


